# -*- coding: utf-8 -*-
"""
HyTools:  Hyperspectral image processing library
Copyright (C) 2021 University of Wisconsin

Authors: Adam Chlus, Zhiwei Ye, Philip Townsend.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, version 3 of the License.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

Initialize hytools
"""
from .base import HyTools

try:
    # First try to read from the file generated by setuptools_scm
    from ._version import version as __version__
except ImportError:
    # Fallback for when the package is installed but _version.py is missing
    try:
        from importlib.metadata import version
        __version__ = version("hy-tools")
    except Exception:
        __version__ = "0.0.1.dev0+unknown"
